

DROP TABLE IF EXISTS "Admins";
DROP TABLE IF EXISTS "GlobalModerators";
DROP TABLE IF EXISTS "Moderators";
DROP TABLE IF EXISTS "DomainBans";
DROP TABLE IF EXISTS "RemovedComments";
DROP TABLE IF EXISTS "Comments";
DROP TABLE IF EXISTS "Paths";
DROP TABLE IF EXISTS "Domains";
DROP TABLE IF EXISTS "Users";
