

DROP TABLE IF EXISTS "Admins";
DROP TABLE IF EXISTS "GlobalModerators";
DROP TABLE IF EXISTS "DomainModerators";
DROP TABLE IF EXISTS "Moderators";
DROP TABLE IF EXISTS "BanActions";
DROP TABLE IF EXISTS "CommentModerationActions";
DROP TABLE IF EXISTS "Logs";
DROP TABLE IF EXISTS "Reports";
DROP TABLE IF EXISTS "DomainBans";
DROP TABLE IF EXISTS "RemovedComments";
DROP TABLE IF EXISTS "VoteRecord";
DROP TABLE IF EXISTS "Comments";
DROP TABLE IF EXISTS "Users";
DROP TABLE IF EXISTS "Paths";
DROP TABLE IF EXISTS "Domains";
